CREATE TABLE IF NOT EXISTS farmers (id SERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(255) UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS fields (id SERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, location VARCHAR(255), latitude DOUBLE PRECISION CHECK (latitude BETWEEN -90 AND 90), longitude DOUBLE PRECISION CHECK (longitude BETWEEN -180 AND 180), size_hectares DOUBLE PRECISION CHECK (size_hectares > 0), farmer_id INTEGER NOT NULL REFERENCES farmers(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS crops (id SERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, planting_date DATE, growth_stage VARCHAR(120), field_id INTEGER NOT NULL REFERENCES fields(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sensors (id SERIAL PRIMARY KEY, serial_number VARCHAR(120) UNIQUE NOT NULL, name VARCHAR(120), sensor_type VARCHAR(80) NOT NULL DEFAULT 'soil_moisture', status VARCHAR(40) NOT NULL DEFAULT 'active', installed_at TIMESTAMPTZ, field_id INTEGER NOT NULL REFERENCES fields(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sensor_readings (id SERIAL PRIMARY KEY, sensor_id INTEGER NOT NULL REFERENCES sensors(id) ON DELETE CASCADE, field_id INTEGER NOT NULL REFERENCES fields(id) ON DELETE CASCADE, soil_moisture DOUBLE PRECISION NOT NULL CHECK (soil_moisture >= 0 AND soil_moisture <= 100), timestamp TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT uq_sensor_reading_timestamp UNIQUE (sensor_id, timestamp));
CREATE TABLE IF NOT EXISTS weather_data (id SERIAL PRIMARY KEY, field_id INTEGER NOT NULL REFERENCES fields(id) ON DELETE CASCADE, recorded_at TIMESTAMPTZ NOT NULL, temperature DOUBLE PRECISION NOT NULL, humidity DOUBLE PRECISION NOT NULL CHECK (humidity BETWEEN 0 AND 100), rainfall DOUBLE PRECISION NOT NULL CHECK (rainfall >= 0), rain_probability DOUBLE PRECISION NOT NULL CHECK (rain_probability BETWEEN 0 AND 100), forecast JSONB NOT NULL DEFAULT '[]', source VARCHAR(120) NOT NULL);
CREATE TABLE IF NOT EXISTS irrigation_history (id SERIAL PRIMARY KEY, field_id INTEGER NOT NULL REFERENCES fields(id) ON DELETE CASCADE, started_at TIMESTAMPTZ NOT NULL, action VARCHAR(80) NOT NULL DEFAULT 'manual', duration_minutes DOUBLE PRECISION NOT NULL, notes TEXT);

ALTER TABLE fields ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE fields ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE fields ADD COLUMN IF NOT EXISTS size_hectares DOUBLE PRECISION;
ALTER TABLE crops ADD COLUMN IF NOT EXISTS growth_stage VARCHAR(120);
ALTER TABLE sensors ADD COLUMN IF NOT EXISTS sensor_type VARCHAR(80) NOT NULL DEFAULT 'soil_moisture';
ALTER TABLE sensors ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'active';
ALTER TABLE sensors ADD COLUMN IF NOT EXISTS installed_at TIMESTAMPTZ;
ALTER TABLE weather_data ADD COLUMN IF NOT EXISTS humidity DOUBLE PRECISION;
ALTER TABLE weather_data ADD COLUMN IF NOT EXISTS rain_probability DOUBLE PRECISION;
ALTER TABLE weather_data ADD COLUMN IF NOT EXISTS forecast JSONB DEFAULT '[]';
ALTER TABLE irrigation_history ADD COLUMN IF NOT EXISTS action VARCHAR(80) NOT NULL DEFAULT 'manual';

INSERT INTO farmers (name, email) VALUES ('Demo Farmer', 'demo@irrigation.local') ON CONFLICT (email) DO NOTHING;
INSERT INTO fields (name, location, latitude, longitude, size_hectares, farmer_id) SELECT 'Demo Field', 'Demo Farm', 17.3850, 78.4867, 1.0, id FROM farmers WHERE email = 'demo@irrigation.local' ON CONFLICT DO NOTHING;
INSERT INTO crops (name, planting_date, field_id) SELECT 'Demo Crop', '2026-08-01', id FROM fields WHERE name = 'Demo Field' AND NOT EXISTS (SELECT 1 FROM crops WHERE name = 'Demo Crop');
INSERT INTO sensors (serial_number, name, field_id) SELECT 'DEMO-SENSOR-001', 'Demo Soil Sensor', id FROM fields WHERE name = 'Demo Field' ON CONFLICT (serial_number) DO NOTHING;